[PROTOCOLS]
ProtocolsSPA = [
    {"tag": "section", "text": "Model Reconstruction", "openItem": "True", "children": [
        {"tag": "protocol_group", "text": "Backbone Reconstruction", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtocolFixerPulchra", "text": "Pulchra (Reconstruct from Ca)"},
            {"tag": "protocol", "value": "ProtocolFixerCg2all", "text": "cg2all (Coarse-Grained to All-Atom)"}
        ]}
    ]}
]

Backbone Reconstruction = [
    [ProtocolFixerPulchra, pulchra_icon.png],
    [ProtocolFixerCg2all, cg2all_icon.png]
]

